### ISSUE TITLE
Does C3 still need nightly (Jun'24)?

### ISSUE THREAD

**Issue by akauppi** [esp-rs/no_std-training#45]
>Furthermore, for ESP32-C3, a [nightly version](https://rust-lang.github.io/rustup/concepts/channels.html#working-with-nightly-rust) of the Rust toolchain is currently required, for this training we will use nightly-2023-11-14 version.

I am trying to debug some stuff, and am only using stable Rust (`rustc` 1.78.0).

I wonder if the above is now outdated.

*tangential*: The problem with having so many "books" is that it's not clear where Espressif official docs end and something else starts. I thought this book to be official, until coming over to the Git side. Not displeased. Just... perhaps we should do something about this?  Rust book. Rust embedded book. Embedded Rust (no_std) on Espressif -- well, even the title states the company name. Hmm 🤔

**Comment by bjoernQ** [comment]
Thanks!

> I am trying to debug some stuff, and am only using stable Rust (rustc 1.78.0).

Probably that is the case. We usually update the training after a HAL release so we should look into that when doing so. In general, we took some effort to don't require nightly wherever we can for the next HAL release

>  I thought this book to be official

I'm not sure I understand this correctly. All projects in the esp-rs GitHub organization are developed with involvement of  Espressif's Rust team (while all projects are fully open source and involve community participation).

Any ideas how to make this more noticeable?

In general, if there is 3rd party content (especially by the Rust-Embedded-WG) we prefer to link to that instead of (partially) duplicate (maybe adapted) content

**Comment by akauppi** [comment]
Thanks for the info, @bjoernQ 

Good to hear you have an update process. Did not know that. The only way I can imagine improving the current situation (things wrapped under `esp-rs` is indeed good) would be to use some “seal of approval” graphical element on the repos that get regular Espressif quality and relevance checks.

**Comment by SergioGasquez** [comment]
Ill be closing the issue as the main question got resolved, feel free to reopen if you have any further question
